defaults:
        - _self_
        - runner: eval
        - dataset: cheetos_tennis
        - model: wasb
        - dataloader: default
        - detector: tracknetv2
        - transform: default
        - tracker: online
hydra:
  run:
    dir: /content/drive/MyDrive/WASB_SBDT/outputs/tennis/${now:%Y-%m-%d_%H-%M-%S}
output_dir: /content/drive/MyDrive/WASB_SBDT/outputs/tennis
seed: 1234

